[build-system]
requires = ["setuptools>=68", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "neurocluster"                   
version = "0.1.1"
description = "Cluster-based permutation testing for neurophysiological data"
readme = "README.md"
requires-python = ">=3.10,<3.13"       # clearly disallow 3.13 for now
license = { text = "MIT" }
authors = [
  { name = "Christina Maher", email = "christina.maher@icahn.mssm.edu" },
  { name = "Alexandra Fink",  email = "alexandra.fink@icahn.mssm.edu" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

dependencies = [
  "numpy>=1.21; python_version < '3.12'",
  "numpy>=1.26; python_version >= '3.12' and python_version < '3.13'",
  "scipy>=1.7;  python_version < '3.12'",
  "scipy>=1.10; python_version >= '3.12' and python_version < '3.13'",
  "statsmodels>=0.12; python_version < '3.12'",
  "statsmodels>=0.14; python_version >= '3.12' and python_version < '3.13'",
  "pandas>=1.3",
  "matplotlib>=3.6",
  "seaborn>=0.11",
  "joblib>=1.0.1"
]

[tool.setuptools.package-data]
NeuroCluster = ["data/*.csv", "data/*.npy"]