[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NeuroCluster"
version = "0.1.0"
description = "Cluster-based statistics for time-resolved electrophysiology"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Christina Maher", email = "christina.maher@icahn.mssm.edu"}, {name = "Alexandra Fink", email = "alexandra.fink@icahn.mssm.edu"}]
dependencies = [
    "joblib==1.0.1",
    "matplotlib>=3.6",
    "numpy==1.21.0",
    "pandas==1.3.0",
    "scipy==1.7.0",
    "seaborn==0.11.0",
    "statsmodels==0.12.2"
]

[tool.setuptools]
packages = ["NeuroCluster"]