[build-system]
requires = ["setuptools>=61", "wheel", "numpy==1.21.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NeuroCluster"
version = "0.1.0"
description = "Cluster-based permutation testing for neurophysiological data"
authors = [
  {name = "Christina Maher", email = "christina.maher@icahn.mssm.edu"},
  {name = "Alexandra Fink", email = "alexandra.fink@icahn.mssm.edu"}
]
readme = "README.md"
requires-python = ">=3.8,<3.11" 
license = {text = "MIT"}
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "numpy>=1.21",
  "pandas>=1.3",
  "matplotlib>=3.6",
  "joblib>=1.0.1",
  "scipy",
  "statsmodels",
  "seaborn"
]
[tool.setuptools.package-data]
"NeuroCluster" = ["data/*.csv", "data/*.npy"]
