name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']   # keep in sync with your supported versions
    env:
      MPLBACKEND: Agg                      # headless matplotlib
      PYTHONWARNINGS: default
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # EITHER install via extras (recommended)...
      - name: Install package (dev/test extras)
        run: pip install -e ".[test]"

      # ...OR (optional) via requirements files; see Section 5 below.
      # - run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Show installed
        run: pip list

      - name: Ensure output dir exists (if tests write files)
        run: mkdir -p tests/test_outputs

      - name: Run tests
        run: pytest -q
