name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      MPLBACKEND: Agg     # headless matplotlib
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # choose ONE of the two install approaches:

      # (A) requirements files:
      - name: Install deps and package
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          pip install -e .

      # (B) OR extras (if you added [project.optional-dependencies].test):
      # - run: pip install -e ".[test]"

      - name: Run unit tests (fast)
        run: pytest -m unit -q

      - name: Run integration tests (E2E)
        run: pytest -m integration -q
