name: Draft PDF

on:
  push:
    paths-ignore:
      - 'paper/paper.pdf'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Check output directory contents
        run: ls -lh paper/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf

      - name: Commit PDF to repo
        run: |
          git config --global user.email "christina@example.com"
          git config --global user.name "Christina Maher"
          git pull
          git add paper/paper.pdf
          git commit -m "Add compiled paper.pdf"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
