name: NeuroCluster CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  unit:
    name: Unit tests (fast)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]   # package supports >=3.8,<3.11
    env:
      MPLBACKEND: Agg            # headless plotting
      PYTHONHASHSEED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run unit tests (marker=unit)
        run: |
          pytest -m unit -q --durations=10

  integration:
    name: Integration test (end-to-end, saves plots)
    runs-on: ubuntu-latest
    needs: unit
    env:
      MPLBACKEND: Agg
      PYTHONHASHSEED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run integration tests (marker=integration)
        run: |
          pytest -m integration -q --durations=10

      - name: Upload integration artifacts (plots & outputs)
        uses: actions/upload-artifact@v4
        with:
          name: neurocluster-test-outputs
          path: tests/test_outputs
          if-no-files-found: ignore   # won't fail if directory not created
