# .github/workflows/tests.yml
name: NeuroCluster CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install package & test deps
        run: |
          pip install -e .
          pip install pytest
      - name: Run unit tests
        run: pytest -m unit -q --durations=10

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install package & test deps
        run: |
          pip install -e .
          pip install pytest
      - name: Run integration tests
        env:
          MPLBACKEND: Agg
        run: pytest -m integration -q --durations=10
      - name: Upload integration artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neurocluster-test-outputs
          path: tests/test_outputs
          if-no-files-found: ignore
